### ISSUE TITLE
USER STORY:  Automatically hide poll as administrator

### ISSUE THREAD

**Issue by greglabo78** [greglabo78/My-First-Agile-Project#9]
In order to  **automatically hide the poll as an administrator** I can **pick the expiry date** while **publishing the poll**

# Acceptance  Criteria
*  **Acceptance Criteria 1**: The poll should disappear  at 11:59 PM on the target date
*  **Acceptance Criteria 2**: The real estate of the "Poll" should be reserved on the home page. a message that says "Stay tuned, a new poll is coming soon" should appear if no other poll is active.
*  **Acceptance Criteria 3**: The administrator expiry date should be at least 3 days after the current date.

# Tasks
- [ ] Task 1: Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Task 2: Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Task 3: Create a Javascript function to validate the expiry date is at least after 3 days
- [ ] Task 4: Create a job to check expired Polls everyday at 11:59 PM and Hide them
- [ ] Task 5: Update the controller function
- [ ] Task 6: Update unit test scripts
- [ ] Task 7: Test functionality
